export const APP_WRITE_ID = 'crm-coffee-rom'
export const DB_ID = 'coffee-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
